var aNavContentData = [
	[
		{
			url:"https://www/kuazhu.com",
			img:"https://cdn.cnbj0.fds.api.mi-img.com/b2c-mimall-media/f515ab05232ed14ccd78ec67e024495a.png",
			name:"小米CC91",
			price:"1791"
		},
		{
			url:"https://www/kuazhu.com",
			img:"https://cdn.cnbj0.fds.api.mi-img.com/b2c-mimall-media/df9b3e7a562e02a33eb069b3f0119815.png",
			name:"小米CC92",
			price:"1792"
		},
		{
			url:"https://www/kuazhu.com",
			img:"https://cdn.cnbj0.fds.api.mi-img.com/b2c-mimall-media/b02f50c9dd2e01c139a06a12502755ef.png",
			name:"小米CC93",
			price:"1793"
		},
		{
			url:"https://www/kuazhu.com",
			img:"https://cdn.cnbj0.fds.api.mi-img.com/b2c-mimall-media/2c9307e9690dfbca39d8de770a7a8664.png",
			name:"小米CC92",
			price:"1792"
		},
		{
			url:"https://www/kuazhu.com",
			img:"https://cdn.cnbj0.fds.api.mi-img.com/b2c-mimall-media/3b5e5829fdf92d54c167f4681531b535.png",
			name:"小米CC92",
			price:"1792"
		},
		{
			url:"https://www/kuazhu.com",
			img:"img/jdshouji1.jpg",
			name:"小米CC92",
			price:"1792"
		},
		{
			url:"https://www/kuazhu.com",
			img:"https://cdn.cnbj1.fds.api.mi-img.com/mi-mall/ae81fdc9f2ed286d135e16c2a5f6db33.png",
			name:"小米CC92",
			price:"1792"
		}
	],
	[
		{
			url:"https://www/kuazhu.com",
			img:"https://cdn.cnbj1.fds.api.mi-img.com/mi-mall/c1937ecb7e9b8e1aee11d6936e19d53c.png",
			name:"小米CC9ssss",
			price:"1799"
		},
		{
			url:"https://www/kuazhu.com",
			img:"https://cdn.cnbj0.fds.api.mi-img.com/b2c-mimall-media/df9b3e7a562e02a33eb069b3f0119815.png",
			name:"小米CC9",
			price:"1799"
		},
		{
			url:"https://www/kuazhu.com",
			img:"https://cdn.cnbj1.fds.api.mi-img.com/mi-mall/dacd6a3d8440b7a038e9778702bd6db6.png",
			name:"小米CC9",
			price:"1799"
		},
		{
			url:"https://www/kuazhu.com",
			img:"https://cdn.cnbj0.fds.api.mi-img.com/b2c-mimall-media/f69828396fcd1e05b932778f4fca4409.jpg",
			name:"小米CC9",
			price:"1799"
		},
		{
			url:"https://www/kuazhu.com",
			img:"img/jdshouji1.jpg",
			name:"小米CC9",
			price:"1799"
		},
		{
			url:"https://www/kuazhu.com",
			img:"https://cdn.cnbj0.fds.api.mi-img.com/b2c-mimall-media/d4fbf37c6b51e510a3bac5e738f2f681.jpg",
			name:"小米CC9ssss",
			price:"1799"
		},
		{
			url:"https://www/kuazhu.com",
			img:"https://cdn.cnbj0.fds.api.mi-img.com/b2c-mimall-media/b0e0c0fda4adf267012815127302f6de.jpg",
			name:"小米CC9ssss",
			price:"1799"
		},

	],
	[
		{
			url:"https://www/kuazhu.com",
			img:"https://cdn.cnbj0.fds.api.mi-img.com/b2c-mimall-media/d4fbf37c6b51e510a3bac5e738f2f681.jpg",
			name:"小米CC9ssss",
			price:"1799"
		},
		{
			url:"https://www/kuazhu.com",
			img:"img/jdshouji1.jpg",
			name:"小米CC9",
			price:"1799"
		},
		{
			url:"https://www/kuazhu.com",
			img:"img/jdshouji1.jpg",
			name:"小米CC9",
			price:"1799"
		},
		{
			url:"https://www/kuazhu.com",
			img:"img/jdshouji1.jpg",
			name:"小米CC9",
			price:"1799"
		},
		{
			url:"https://www/kuazhu.com",
			img:"img/jdshouji1.jpg",
			name:"小米CC9",
			price:"1799"
		}
	],
	[
		{
			url:"https://www/kuazhu.com",
			img:"img/jdshouji1.jpg",
			name:"小米CC9ssss",
			price:"1799"
		},
		{
			url:"https://www/kuazhu.com",
			img:"img/jdshouji1.jpg",
			name:"小米CC9",
			price:"1799"
		},
		{
			url:"https://www/kuazhu.com",
			img:"img/jdshouji1.jpg",
			name:"小米CC9",
			price:"1799"
		},
		{
			url:"https://www/kuazhu.com",
			img:"img/jdshouji1.jpg",
			name:"小米CC9",
			price:"1799"
		},
		{
			url:"https://www/kuazhu.com",
			img:"img/jdshouji1.jpg",
			name:"小米CC9",
			price:"1799"
		}
	],
	[
		{
			url:"https://www/kuazhu.com",
			img:"img/jdshouji1.jpg",
			name:"小米CC9ssss",
			price:"1799"
		},
		{
			url:"https://www/kuazhu.com",
			img:"img/jdshouji1.jpg",
			name:"小米CC9",
			price:"1799"
		},
		{
			url:"https://www/kuazhu.com",
			img:"img/jdshouji1.jpg",
			name:"小米CC9",
			price:"1799"
		},
		{
			url:"https://www/kuazhu.com",
			img:"img/jdshouji1.jpg",
			name:"小米CC9",
			price:"1799"
		},
		{
			url:"https://www/kuazhu.com",
			img:"img/jdshouji1.jpg",
			name:"小米CC9",
			price:"1799"
		}
	],
];

var aCateContentData = [
	[
		{
			url:"https://www.kuazhu.com",
			img:"img/jdshouji1.jpg",
			name:"小米手机1-1"
		},
		{
			url:"https://www.kuazhu.com",
			img:"img/jdshouji1.jpg",
			name:"小米手机1-2"
		},
		{
			url:"https://www.kuazhu.com",
			img:"img/jdshouji1.jpg",
			name:"小米手机1-3"
		},
		{
			url:"https://www.kuazhu.com",
			img:"img/jdshouji1.jpg",
			name:"小米手机1-4"
		}
	],
	[
		{
			url:"https://www.kuazhu.com",
			img:"img/jdshouji1.jpg",
			name:"小米手机2-1"
		},
		{
			url:"https://www.kuazhu.com",
			img:"img/jdshouji1.jpg",
			name:"小米手机2-2"
		},
		{
			url:"https://www.kuazhu.com",
			img:"img/jdshouji1.jpg",
			name:"小米手机2-3"
		},
		{
			url:"https://www.kuazhu.com",
			img:"img/jdshouji1.jpg",
			name:"小米手机2-4"
		},
		{
			url:"https://www.kuazhu.com",
			img:"img/jdshouji1.jpg",
			name:"小米手机2-5"
		},
		{
			url:"https://www.kuazhu.com",
			img:"img/jdshouji1.jpg",
			name:"小米手机2-6"
		}
	],
	[
		{
			url:"https://www.kuazhu.com",
			img:"img/jdshouji1.jpg",
			name:"小米手机3-1"
		},
		{
			url:"https://www.kuazhu.com",
			img:"img/jdshouji1.jpg",
			name:"小米手机3-2"
		}
	],
	[
		{
			url:"https://www.kuazhu.com",
			img:"img/jdshouji1.jpg",
			name:"小米手机4-1"
		}
	]
];

var aTabContentData = [
	[
		{
			url:"https://www.kuazhu.com",
			img:"img/jdshangou1.jpg",
			name:"小米游戏本第一页",
			desc:"冷酷的性能怪兽",
			price:"5999",
			del:"7999",
			flag:{
				name:"flag-jian",
				content:"立减200元"
			},
			comment:{
				content:"我是来做评论的哈哈哈哈哈哈哈哈哈",
				author:"kuazhu"
			}
		},
		{
			url:"https://www.kuazhu.com",
			img:"img/jdshangou1.jpg",
			name:"小米游戏本15.6 '8代i5 8G 1T 我是被省略的",
			desc:"冷酷的性能怪兽",
			price:"5999",
			del:"7999",
			comment:{
				content:"我是来做评论的哈哈哈哈哈哈哈哈哈",
				author:"kuazhu"
			}
		},
		{
			url:"https://www.kuazhu.com",
			img:"img/jdshangou1.jpg",
			name:"小米游戏本15.6 '8代i5 8G 1T 我是被省略的",
			desc:"冷酷的性能怪兽",
			price:"5999",
			del:"7999",
			flag:{
				name:"flag-new",
				content:"新品"
			}
		},
		{
			url:"https://www.kuazhu.com",
			img:"img/jdshangou1.jpg",
			name:"小米游戏本15.6 '8代i5 8G 1T 我是被省略的",
			desc:"冷酷的性能怪兽",
			price:"5999",
			del:"7999",
			flag:{
				name:"flag-jian",
				content:"立减200元"
			},
			comment:{
				content:"我是来做评论的哈哈哈哈哈哈哈哈哈",
				author:"kuazhu"
			}
		},
		{
			url:"https://www.kuazhu.com",
			img:"img/jdshangou1.jpg",
			name:"小米游戏本15.6 '8代i5 8G 1T 我是被省略的",
			desc:"冷酷的性能怪兽",
			price:"5999",
			del:"7999",
			flag:{
				name:"flag-jian",
				content:"立减200元"
			},
			comment:{
				content:"我是来做评论的哈哈哈哈哈哈哈哈哈",
				author:"kuazhu"
			}
		},
		{
			url:"https://www.kuazhu.com",
			img:"img/jdshangou1.jpg",
			name:"小米游戏本15.6 '8代i5 8G 1T 我是被省略的",
			desc:"冷酷的性能怪兽",
			price:"5999",
			del:"7999",
			flag:{
				name:"flag-jian",
				content:"立减200元"
			},
			comment:{
				content:"我是来做评论的哈哈哈哈哈哈哈哈哈",
				author:"kuazhu"
			}
		},
		{
			url:"https://www.kuazhu.com",
			img:"img/jdshangou1.jpg",
			name:"小米游戏本15.6 '8代i5 8G 1T 我是被省略的",
			desc:"冷酷的性能怪兽",
			price:"5999",
			del:"7999",
			flag:{
				name:"flag-jian",
				content:"立减200元"
			},
			comment:{
				content:"我是来做评论的哈哈哈哈哈哈哈哈哈",
				author:"kuazhu"
			}
		},
		{
			top:{
				desc:"米家电烤箱",
				price:"299",
				url:"https://www.kuazhu.com",
				img:"img/jddkx.png"
			},
			bottom:{
				name:"热门",
				url:"https://www.kuazhu.com",
				img:"img/jdjiantou.png"
			}
		}
	],
	[
		{
			url:"https://www.kuazhu.com",
			img:"img/jdshangou1.jpg",
			name:"小米游戏本15.6第二页",
			desc:"冷酷的性能怪兽",
			price:"5999",
			del:"7999",
			flag:{
				name:"flag-jian",
				content:"立减200元"
			},
			comment:{
				content:"我是来做评论的哈哈哈哈哈哈哈哈哈",
				author:"kuazhu"
			}
		},
		{
			url:"https://www.kuazhu.com",
			img:"img/jdshangou1.jpg",
			name:"小米游戏本15.6 '8代i5 8G 1T 我是被省略的",
			desc:"冷酷的性能怪兽",
			price:"5999",
			del:"7999",
			flag:{
				name:"flag-jian",
				content:"立减200元"
			},
			comment:{
				content:"我是来做评论的哈哈哈哈哈哈哈哈哈",
				author:"kuazhu"
			}
		},
		{
			url:"https://www.kuazhu.com",
			img:"img/jdshangou1.jpg",
			name:"小米游戏本15.6 '8代i5 8G 1T 我是被省略的",
			desc:"冷酷的性能怪兽",
			price:"5999",
			del:"7999",
			flag:{
				name:"flag-jian",
				content:"立减200元"
			},
			comment:{
				content:"我是来做评论的哈哈哈哈哈哈哈哈哈",
				author:"kuazhu"
			}
		},
		{
			url:"https://www.kuazhu.com",
			img:"img/jdshangou1.jpg",
			name:"小米游戏本15.6 '8代i5 8G 1T 我是被省略的",
			desc:"冷酷的性能怪兽",
			price:"5999",
			del:"7999",
			flag:{
				name:"flag-jian",
				content:"立减200元"
			},
			comment:{
				content:"我是来做评论的哈哈哈哈哈哈哈哈哈",
				author:"kuazhu"
			}
		},
		{
			url:"https://www.kuazhu.com",
			img:"img/jdshangou1.jpg",
			name:"小米游戏本15.6 '8代i5 8G 1T 我是被省略的",
			desc:"冷酷的性能怪兽",
			price:"5999",
			del:"7999",
			flag:{
				name:"flag-jian",
				content:"立减200元"
			},
			comment:{
				content:"我是来做评论的哈哈哈哈哈哈哈哈哈",
				author:"kuazhu"
			}
		},
		{
			url:"https://www.kuazhu.com",
			img:"img/jdshangou1.jpg",
			name:"小米游戏本15.6 '8代i5 8G 1T 我是被省略的",
			desc:"冷酷的性能怪兽",
			price:"5999",
			del:"7999",
			flag:{
				name:"flag-jian",
				content:"立减200元"
			},
			comment:{
				content:"我是来做评论的哈哈哈哈哈哈哈哈哈",
				author:"kuazhu"
			}
		},
		{
			url:"https://www.kuazhu.com",
			img:"img/jdshangou1.jpg",
			name:"小米游戏本15.6 '8代i5 8G 1T 我是被省略的",
			desc:"冷酷的性能怪兽",
			price:"5999",
			del:"7999",
			flag:{
				name:"flag-jian",
				content:"立减200元"
			},
			comment:{
				content:"我是来做评论的哈哈哈哈哈哈哈哈哈",
				author:"kuazhu"
			}
		},
		{
			top:{
				desc:"米家电烤箱",
				price:"299",
				url:"https://www.kuazhu.com",
				img:"img/jddkx.png"
			},
			bottom:{
				name:"热门",
				url:"https://www.kuazhu.com",
				img:"img/jdjiantou.png"
			}
		}
	],
	[
		{
			url:"https://www.kuazhu.com",
			img:"img/jdshangou1.jpg",
			name:"小米游戏本15.6 第三页",
			desc:"冷酷的性能怪兽",
			price:"5999",
			del:"7999",
			flag:{
				name:"flag-jian",
				content:"立减200元"
			},
			comment:{
				content:"我是来做评论的哈哈哈哈哈哈哈哈哈",
				author:"kuazhu"
			}
		},
		{
			url:"https://www.kuazhu.com",
			img:"img/jdshangou1.jpg",
			name:"小米游戏本15.6 '8代i5 8G 1T 我是被省略的",
			desc:"冷酷的性能怪兽",
			price:"5999",
			del:"7999",
			flag:{
				name:"flag-jian",
				content:"立减200元"
			},
			comment:{
				content:"我是来做评论的哈哈哈哈哈哈哈哈哈",
				author:"kuazhu"
			}
		},
		{
			url:"https://www.kuazhu.com",
			img:"img/jdshangou1.jpg",
			name:"小米游戏本15.6 '8代i5 8G 1T 我是被省略的",
			desc:"冷酷的性能怪兽",
			price:"5999",
			del:"7999",
			flag:{
				name:"flag-jian",
				content:"立减200元"
			},
			comment:{
				content:"我是来做评论的哈哈哈哈哈哈哈哈哈",
				author:"kuazhu"
			}
		},
		{
			url:"https://www.kuazhu.com",
			img:"img/jdshangou1.jpg",
			name:"小米游戏本15.6 '8代i5 8G 1T 我是被省略的",
			desc:"冷酷的性能怪兽",
			price:"5999",
			del:"7999",
			flag:{
				name:"flag-jian",
				content:"立减200元"
			},
			comment:{
				content:"我是来做评论的哈哈哈哈哈哈哈哈哈",
				author:"kuazhu"
			}
		},
		{
			url:"https://www.kuazhu.com",
			img:"img/jdshangou1.jpg",
			name:"小米游戏本15.6 '8代i5 8G 1T 我是被省略的",
			desc:"冷酷的性能怪兽",
			price:"5999",
			del:"7999",
			flag:{
				name:"flag-jian",
				content:"立减200元"
			},
			comment:{
				content:"我是来做评论的哈哈哈哈哈哈哈哈哈",
				author:"kuazhu"
			}
		},
		{
			url:"https://www.kuazhu.com",
			img:"img/jdshangou1.jpg",
			name:"小米游戏本15.6 '8代i5 8G 1T 我是被省略的",
			desc:"冷酷的性能怪兽",
			price:"5999",
			del:"7999",
			flag:{
				name:"flag-jian",
				content:"立减200元"
			},
			comment:{
				content:"我是来做评论的哈哈哈哈哈哈哈哈哈",
				author:"kuazhu"
			}
		},
		{
			url:"https://www.kuazhu.com",
			img:"img/jdshangou1.jpg",
			name:"小米游戏本15.6 '8代i5 8G 1T 我是被省略的",
			desc:"冷酷的性能怪兽",
			price:"5999",
			del:"7999",
			flag:{
				name:"flag-jian",
				content:"立减200元"
			},
			comment:{
				content:"我是来做评论的哈哈哈哈哈哈哈哈哈",
				author:"kuazhu"
			}
		},
		{
			top:{
				desc:"米家电烤箱",
				price:"299",
				url:"https://www.kuazhu.com",
				img:"img/jddkx.png"
			},
			bottom:{
				name:"热门",
				url:"https://www.kuazhu.com",
				img:"img/jdjiantou.png"
			}
		}
	],
	[
		{
			url:"https://www.kuazhu.com",
			img:"img/jdshangou1.jpg",
			name:"小米游戏本15.6 第四页",
			desc:"冷酷的性能怪兽",
			price:"5999",
			del:"7999",
			flag:{
				name:"flag-jian",
				content:"立减200元"
			},
			comment:{
				content:"我是来做评论的哈哈哈哈哈哈哈哈哈",
				author:"kuazhu"
			}
		},
		{
			url:"https://www.kuazhu.com",
			img:"img/jdshangou1.jpg",
			name:"小米游戏本15.6 '8代i5 8G 1T 我是被省略的",
			desc:"冷酷的性能怪兽",
			price:"5999",
			del:"7999",
			flag:{
				name:"flag-jian",
				content:"立减200元"
			},
			comment:{
				content:"我是来做评论的哈哈哈哈哈哈哈哈哈",
				author:"kuazhu"
			}
		},
		{
			url:"https://www.kuazhu.com",
			img:"img/jdshangou1.jpg",
			name:"小米游戏本15.6 '8代i5 8G 1T 我是被省略的",
			desc:"冷酷的性能怪兽",
			price:"5999",
			del:"7999",
			flag:{
				name:"flag-jian",
				content:"立减200元"
			},
			comment:{
				content:"我是来做评论的哈哈哈哈哈哈哈哈哈",
				author:"kuazhu"
			}
		},
		{
			url:"https://www.kuazhu.com",
			img:"img/jdshangou1.jpg",
			name:"小米游戏本15.6 '8代i5 8G 1T 我是被省略的",
			desc:"冷酷的性能怪兽",
			price:"5999",
			del:"7999",
			flag:{
				name:"flag-jian",
				content:"立减200元"
			},
			comment:{
				content:"我是来做评论的哈哈哈哈哈哈哈哈哈",
				author:"kuazhu"
			}
		},
		{
			url:"https://www.kuazhu.com",
			img:"img/jdshangou1.jpg",
			name:"小米游戏本15.6 '8代i5 8G 1T 我是被省略的",
			desc:"冷酷的性能怪兽",
			price:"5999",
			del:"7999",
			flag:{
				name:"flag-jian",
				content:"立减200元"
			},
			comment:{
				content:"我是来做评论的哈哈哈哈哈哈哈哈哈",
				author:"kuazhu"
			}
		},
		{
			url:"https://www.kuazhu.com",
			img:"img/jdshangou1.jpg",
			name:"小米游戏本15.6 '8代i5 8G 1T 我是被省略的",
			desc:"冷酷的性能怪兽",
			price:"5999",
			del:"7999",
			flag:{
				name:"flag-jian",
				content:"立减200元"
			},
			comment:{
				content:"我是来做评论的哈哈哈哈哈哈哈哈哈",
				author:"kuazhu"
			}
		},
		{
			url:"https://www.kuazhu.com",
			img:"img/jdshangou1.jpg",
			name:"小米游戏本15.6 '8代i5 8G 1T 我是被省略的",
			desc:"冷酷的性能怪兽",
			price:"5999",
			del:"7999",
			flag:{
				name:"flag-jian",
				content:"立减200元"
			},
			comment:{
				content:"我是来做评论的哈哈哈哈哈哈哈哈哈",
				author:"kuazhu"
			}
		},
		{
			top:{
				desc:"米家电烤箱",
				price:"299",
				url:"https://www.kuazhu.com",
				img:"img/jddkx.png"
			},
			bottom:{
				name:"热门",
				url:"https://www.kuazhu.com",
				img:"img/jdjiantou.png"
			}
		}
	]
];
