var aNavContentData = [
	[
		{
			url:"https://www/kuazhu.com",
			img:"img/shshouji1.jpg",
			name:"小米CC91",
			price:"1791"
		},
		{
			url:"https://www/kuazhu.com",
			img:"img/shshouji1.jpg",
			name:"小米CC92",
			price:"1792"
		},
		{
			url:"https://www/kuazhu.com",
			img:"img/shshouji1.jpg",
			name:"小米CC93",
			price:"1793"
		},
		{
			url:"https://www/kuazhu.com",
			img:"img/shshouji1.jpg",
			name:"小米CC92",
			price:"1792"
		},{
			url:"https://www/kuazhu.com",
			img:"img/shshouji1.jpg",
			name:"小米CC92",
			price:"1792"
		},{
			url:"https://www/kuazhu.com",
			img:"img/shshouji1.jpg",
			name:"小米CC92",
			price:"1792"
		},{
			url:"https://www/kuazhu.com",
			img:"img/shshouji1.jpg",
			name:"小米CC92",
			price:"1792"
		},
	],
	[
		{
			url:"https://www/kuazhu.com",
			img:"https://cdn.cnbj1.fds.api.mi-img.com/mi-mall/41c566d825a3ae3b5751a78d4c7cffdb.png",
			name:"小米CC9ssss",
			price:"1799"
		},
		{
			url:"https://www/kuazhu.com",
			img:"https://cdn.cnbj1.fds.api.mi-img.com/mi-mall/41c566d825a3ae3b5751a78d4c7cffdb.png",
			name:"小米CC9ssss",
			price:"1799"
		},
		{
			url:"https://www/kuazhu.com",
			img:"https://cdn.cnbj1.fds.api.mi-img.com/mi-mall/41c566d825a3ae3b5751a78d4c7cffdb.png",
			name:"小米CC9ssss",
			price:"1799"
		},
		{
			url:"https://www/kuazhu.com",
			img:"https://cdn.cnbj1.fds.api.mi-img.com/mi-mall/41c566d825a3ae3b5751a78d4c7cffdb.png",
			name:"小米CC9ssss",
			price:"1799"
		},
		{
			url:"https://www/kuazhu.com",
			img:"https://cdn.cnbj1.fds.api.mi-img.com/mi-mall/41c566d825a3ae3b5751a78d4c7cffdb.png",
			name:"小米CC9ssss",
			price:"1799"
		},
		{
			url:"https://www/kuazhu.com",
			img:"https://cdn.cnbj1.fds.api.mi-img.com/mi-mall/41c566d825a3ae3b5751a78d4c7cffdb.png",
			name:"小米CC9ssss",
			price:"1799"
		}
	],
	[
		{
			url:"https://www/kuazhu.com",
			img:"https://cdn.cnbj1.fds.api.mi-img.com/mi-mall/c1937ecb7e9b8e1aee11d6936e19d53c.png",
			name:"小米CC9ssss",
			price:"1799"
		},
		{
			url:"https://www/kuazhu.com",
			img:"https://cdn.cnbj1.fds.api.mi-img.com/mi-mall/c1937ecb7e9b8e1aee11d6936e19d53c.png",
			name:"小米CC9ssss",
			price:"1799"
		},
		{
			url:"https://www/kuazhu.com",
			img:"https://cdn.cnbj1.fds.api.mi-img.com/mi-mall/c1937ecb7e9b8e1aee11d6936e19d53c.png",
			name:"小米CC9ssss",
			price:"1799"
		},
		{
			url:"https://www/kuazhu.com",
			img:"https://cdn.cnbj1.fds.api.mi-img.com/mi-mall/c1937ecb7e9b8e1aee11d6936e19d53c.png",
			name:"小米CC9ssss",
			price:"1799"
		},
		{
			url:"https://www/kuazhu.com",
			img:"https://cdn.cnbj1.fds.api.mi-img.com/mi-mall/c1937ecb7e9b8e1aee11d6936e19d53c.png",
			name:"小米CC9ssss",
			price:"1799"
		},
		{
			url:"https://www/kuazhu.com",
			img:"https://cdn.cnbj1.fds.api.mi-img.com/mi-mall/c1937ecb7e9b8e1aee11d6936e19d53c.png",
			name:"小米CC9ssss",
			price:"1799"
		}
	],
	[
		{
			url:"https://www/kuazhu.com",
			img:"img/shshouji1.jpg",
			name:"小米CC9ssss",
			price:"1799"
		},
		{
			url:"https://www/kuazhu.com",
			img:"img/shshouji1.jpg",
			name:"小米CC9",
			price:"1799"
		},
		{
			url:"https://www/kuazhu.com",
			img:"img/shshouji1.jpg",
			name:"小米CC9",
			price:"1799"
		},
		{
			url:"https://www/kuazhu.com",
			img:"img/shshouji1.jpg",
			name:"小米CC9",
			price:"1799"
		},
		{
			url:"https://www/kuazhu.com",
			img:"img/shshouji1.jpg",
			name:"小米CC9",
			price:"1799"
		}
	],
	[
		{
			url:"https://www/kuazhu.com",
			img:"img/shshouji1.jpg",
			name:"小米CC9ssss",
			price:"1799"
		},
		{
			url:"https://www/kuazhu.com",
			img:"img/shshouji1.jpg",
			name:"小米CC9",
			price:"1799"
		},
		{
			url:"https://www/kuazhu.com",
			img:"img/shshouji1.jpg",
			name:"小米CC9",
			price:"1799"
		},
		{
			url:"https://www/kuazhu.com",
			img:"img/shshouji1.jpg",
			name:"小米CC9",
			price:"1799"
		},
		{
			url:"https://www/kuazhu.com",
			img:"img/shshouji1.jpg",
			name:"小米CC9",
			price:"1799"
		}
	],
];

var aCateContentData = [
	[
		{
			url:"https://www.kuazhu.com",
			img:"img/shshouji1.jpg",
			name:"小米手机1-1"
		},
		{
			url:"https://www.kuazhu.com",
			img:"img/shshouji1.jpg",
			name:"小米手机1-2"
		},
		{
			url:"https://www.kuazhu.com",
			img:"img/shshouji1.jpg",
			name:"小米手机1-3"
		},
		{
			url:"https://www.kuazhu.com",
			img:"img/shshouji1.jpg",
			name:"小米手机1-4"
		}
	],
	[
		{
			url:"https://www.kuazhu.com",
			img:"img/shshouji1.jpg",
			name:"小米手机2-1"
		},
		{
			url:"https://www.kuazhu.com",
			img:"img/shshouji1.jpg",
			name:"小米手机2-2"
		},
		{
			url:"https://www.kuazhu.com",
			img:"img/shshouji1.jpg",
			name:"小米手机2-3"
		},
		{
			url:"https://www.kuazhu.com",
			img:"img/shshouji1.jpg",
			name:"小米手机2-4"
		},
		{
			url:"https://www.kuazhu.com",
			img:"img/shshouji1.jpg",
			name:"小米手机2-5"
		},
		{
			url:"https://www.kuazhu.com",
			img:"img/shshouji1.jpg",
			name:"小米手机2-6"
		}
	],
	[
		{
			url:"https://www.kuazhu.com",
			img:"img/shshouji1.jpg",
			name:"小米手机3-1"
		},
		{
			url:"https://www.kuazhu.com",
			img:"img/shshouji1.jpg",
			name:"小米手机3-2"
		}
	],
	[
		{
			url:"https://www.kuazhu.com",
			img:"img/shshouji1.jpg",
			name:"小米手机4-1"
		}
	]
];

var aTabContentData = [
	[
		{
			url:"https://www.kuazhu.com",
			img:"img/shshangou1.jpg",
			name:"小米游戏本第一页",
			desc:"冷酷的性能怪兽",
			price:"5999",
			del:"7999",
			flag:{
				name:"flag-jian",
				content:"立减200元"
			},
			comment:{
				content:"我是来做评论的哈哈哈哈哈哈哈哈哈",
				author:"kuazhu"
			}
		},
		{
			url:"https://www.kuazhu.com",
			img:"img/shshangou1.jpg",
			name:"小米游戏本15.6 '8代i5 8G 1T 我是被省略的",
			desc:"冷酷的性能怪兽",
			price:"5999",
			del:"7999",
			comment:{
				content:"我是来做评论的哈哈哈哈哈哈哈哈哈",
				author:"kuazhu"
			}
		},
		{
			url:"https://www.kuazhu.com",
			img:"img/shshangou1.jpg",
			name:"小米游戏本15.6 '8代i5 8G 1T 我是被省略的",
			desc:"冷酷的性能怪兽",
			price:"5999",
			del:"7999",
			flag:{
				name:"flag-new",
				content:"新品"
			}
		},
		{
			url:"https://www.kuazhu.com",
			img:"img/shshangou1.jpg",
			name:"小米游戏本15.6 '8代i5 8G 1T 我是被省略的",
			desc:"冷酷的性能怪兽",
			price:"5999",
			del:"7999",
			flag:{
				name:"flag-jian",
				content:"立减200元"
			},
			comment:{
				content:"我是来做评论的哈哈哈哈哈哈哈哈哈",
				author:"kuazhu"
			}
		},
		{
			url:"https://www.kuazhu.com",
			img:"img/shshangou1.jpg",
			name:"小米游戏本15.6 '8代i5 8G 1T 我是被省略的",
			desc:"冷酷的性能怪兽",
			price:"5999",
			del:"7999",
			flag:{
				name:"flag-jian",
				content:"立减200元"
			},
			comment:{
				content:"我是来做评论的哈哈哈哈哈哈哈哈哈",
				author:"kuazhu"
			}
		},
		{
			url:"https://www.kuazhu.com",
			img:"img/shshangou1.jpg",
			name:"小米游戏本15.6 '8代i5 8G 1T 我是被省略的",
			desc:"冷酷的性能怪兽",
			price:"5999",
			del:"7999",
			flag:{
				name:"flag-jian",
				content:"立减200元"
			},
			comment:{
				content:"我是来做评论的哈哈哈哈哈哈哈哈哈",
				author:"kuazhu"
			}
		},
		{
			url:"https://www.kuazhu.com",
			img:"img/shshangou1.jpg",
			name:"小米游戏本15.6 '8代i5 8G 1T 我是被省略的",
			desc:"冷酷的性能怪兽",
			price:"5999",
			del:"7999",
			flag:{
				name:"flag-jian",
				content:"立减200元"
			},
			comment:{
				content:"我是来做评论的哈哈哈哈哈哈哈哈哈",
				author:"kuazhu"
			}
		},
		{
			top:{
				desc:"米家电烤箱",
				price:"299",
				url:"https://www.kuazhu.com",
				img:"img/shdkx.png"
			},
			bottom:{
				name:"热门",
				url:"https://www.kuazhu.com",
				img:"img/shjiantou.png"
			}
		}
	],
	[
		{
			url:"https://www.kuazhu.com",
			img:"img/shshangou1.jpg",
			name:"小米游戏本15.6第二页",
			desc:"冷酷的性能怪兽",
			price:"5999",
			del:"7999",
			flag:{
				name:"flag-jian",
				content:"立减200元"
			},
			comment:{
				content:"我是来做评论的哈哈哈哈哈哈哈哈哈",
				author:"kuazhu"
			}
		},
		{
			url:"https://www.kuazhu.com",
			img:"img/shshangou1.jpg",
			name:"小米游戏本15.6 '8代i5 8G 1T 我是被省略的",
			desc:"冷酷的性能怪兽",
			price:"5999",
			del:"7999",
			flag:{
				name:"flag-jian",
				content:"立减200元"
			},
			comment:{
				content:"我是来做评论的哈哈哈哈哈哈哈哈哈",
				author:"kuazhu"
			}
		},
		{
			url:"https://www.kuazhu.com",
			img:"img/shshangou1.jpg",
			name:"小米游戏本15.6 '8代i5 8G 1T 我是被省略的",
			desc:"冷酷的性能怪兽",
			price:"5999",
			del:"7999",
			flag:{
				name:"flag-jian",
				content:"立减200元"
			},
			comment:{
				content:"我是来做评论的哈哈哈哈哈哈哈哈哈",
				author:"kuazhu"
			}
		},
		{
			url:"https://www.kuazhu.com",
			img:"img/shshangou1.jpg",
			name:"小米游戏本15.6 '8代i5 8G 1T 我是被省略的",
			desc:"冷酷的性能怪兽",
			price:"5999",
			del:"7999",
			flag:{
				name:"flag-jian",
				content:"立减200元"
			},
			comment:{
				content:"我是来做评论的哈哈哈哈哈哈哈哈哈",
				author:"kuazhu"
			}
		},
		{
			url:"https://www.kuazhu.com",
			img:"img/shshangou1.jpg",
			name:"小米游戏本15.6 '8代i5 8G 1T 我是被省略的",
			desc:"冷酷的性能怪兽",
			price:"5999",
			del:"7999",
			flag:{
				name:"flag-jian",
				content:"立减200元"
			},
			comment:{
				content:"我是来做评论的哈哈哈哈哈哈哈哈哈",
				author:"kuazhu"
			}
		},
		{
			url:"https://www.kuazhu.com",
			img:"img/shshangou1.jpg",
			name:"小米游戏本15.6 '8代i5 8G 1T 我是被省略的",
			desc:"冷酷的性能怪兽",
			price:"5999",
			del:"7999",
			flag:{
				name:"flag-jian",
				content:"立减200元"
			},
			comment:{
				content:"我是来做评论的哈哈哈哈哈哈哈哈哈",
				author:"kuazhu"
			}
		},
		{
			url:"https://www.kuazhu.com",
			img:"img/shshangou1.jpg",
			name:"小米游戏本15.6 '8代i5 8G 1T 我是被省略的",
			desc:"冷酷的性能怪兽",
			price:"5999",
			del:"7999",
			flag:{
				name:"flag-jian",
				content:"立减200元"
			},
			comment:{
				content:"我是来做评论的哈哈哈哈哈哈哈哈哈",
				author:"kuazhu"
			}
		},
		{
			top:{
				desc:"米家电烤箱",
				price:"299",
				url:"https://www.kuazhu.com",
				img:"img/shdkx.png"
			},
			bottom:{
				name:"热门",
				url:"https://www.kuazhu.com",
				img:"img/shjiantou.png"
			}
		}
	],
	[
		{
			url:"https://www.kuazhu.com",
			img:"img/shshangou1.jpg",
			name:"小米游戏本15.6 第三页",
			desc:"冷酷的性能怪兽",
			price:"5999",
			del:"7999",
			flag:{
				name:"flag-jian",
				content:"立减200元"
			},
			comment:{
				content:"我是来做评论的哈哈哈哈哈哈哈哈哈",
				author:"kuazhu"
			}
		},
		{
			url:"https://www.kuazhu.com",
			img:"img/shshangou1.jpg",
			name:"小米游戏本15.6 '8代i5 8G 1T 我是被省略的",
			desc:"冷酷的性能怪兽",
			price:"5999",
			del:"7999",
			flag:{
				name:"flag-jian",
				content:"立减200元"
			},
			comment:{
				content:"我是来做评论的哈哈哈哈哈哈哈哈哈",
				author:"kuazhu"
			}
		},
		{
			url:"https://www.kuazhu.com",
			img:"img/shshangou1.jpg",
			name:"小米游戏本15.6 '8代i5 8G 1T 我是被省略的",
			desc:"冷酷的性能怪兽",
			price:"5999",
			del:"7999",
			flag:{
				name:"flag-jian",
				content:"立减200元"
			},
			comment:{
				content:"我是来做评论的哈哈哈哈哈哈哈哈哈",
				author:"kuazhu"
			}
		},
		{
			url:"https://www.kuazhu.com",
			img:"img/shshangou1.jpg",
			name:"小米游戏本15.6 '8代i5 8G 1T 我是被省略的",
			desc:"冷酷的性能怪兽",
			price:"5999",
			del:"7999",
			flag:{
				name:"flag-jian",
				content:"立减200元"
			},
			comment:{
				content:"我是来做评论的哈哈哈哈哈哈哈哈哈",
				author:"kuazhu"
			}
		},
		{
			url:"https://www.kuazhu.com",
			img:"img/shshangou1.jpg",
			name:"小米游戏本15.6 '8代i5 8G 1T 我是被省略的",
			desc:"冷酷的性能怪兽",
			price:"5999",
			del:"7999",
			flag:{
				name:"flag-jian",
				content:"立减200元"
			},
			comment:{
				content:"我是来做评论的哈哈哈哈哈哈哈哈哈",
				author:"kuazhu"
			}
		},
		{
			url:"https://www.kuazhu.com",
			img:"img/shshangou1.jpg",
			name:"小米游戏本15.6 '8代i5 8G 1T 我是被省略的",
			desc:"冷酷的性能怪兽",
			price:"5999",
			del:"7999",
			flag:{
				name:"flag-jian",
				content:"立减200元"
			},
			comment:{
				content:"我是来做评论的哈哈哈哈哈哈哈哈哈",
				author:"kuazhu"
			}
		},
		{
			url:"https://www.kuazhu.com",
			img:"img/shshangou1.jpg",
			name:"小米游戏本15.6 '8代i5 8G 1T 我是被省略的",
			desc:"冷酷的性能怪兽",
			price:"5999",
			del:"7999",
			flag:{
				name:"flag-jian",
				content:"立减200元"
			},
			comment:{
				content:"我是来做评论的哈哈哈哈哈哈哈哈哈",
				author:"kuazhu"
			}
		},
		{
			top:{
				desc:"米家电烤箱",
				price:"299",
				url:"https://www.kuazhu.com",
				img:"img/shdkx.png"
			},
			bottom:{
				name:"热门",
				url:"https://www.kuazhu.com",
				img:"img/shjiantou.png"
			}
		}
	],
	[
		{
			url:"https://www.kuazhu.com",
			img:"img/shshangou1.jpg",
			name:"小米游戏本15.6 第四页",
			desc:"冷酷的性能怪兽",
			price:"5999",
			del:"7999",
			flag:{
				name:"flag-jian",
				content:"立减200元"
			},
			comment:{
				content:"我是来做评论的哈哈哈哈哈哈哈哈哈",
				author:"kuazhu"
			}
		},
		{
			url:"https://www.kuazhu.com",
			img:"img/shshangou1.jpg",
			name:"小米游戏本15.6 '8代i5 8G 1T 我是被省略的",
			desc:"冷酷的性能怪兽",
			price:"5999",
			del:"7999",
			flag:{
				name:"flag-jian",
				content:"立减200元"
			},
			comment:{
				content:"我是来做评论的哈哈哈哈哈哈哈哈哈",
				author:"kuazhu"
			}
		},
		{
			url:"https://www.kuazhu.com",
			img:"img/shshangou1.jpg",
			name:"小米游戏本15.6 '8代i5 8G 1T 我是被省略的",
			desc:"冷酷的性能怪兽",
			price:"5999",
			del:"7999",
			flag:{
				name:"flag-jian",
				content:"立减200元"
			},
			comment:{
				content:"我是来做评论的哈哈哈哈哈哈哈哈哈",
				author:"kuazhu"
			}
		},
		{
			url:"https://www.kuazhu.com",
			img:"img/shshangou1.jpg",
			name:"小米游戏本15.6 '8代i5 8G 1T 我是被省略的",
			desc:"冷酷的性能怪兽",
			price:"5999",
			del:"7999",
			flag:{
				name:"flag-jian",
				content:"立减200元"
			},
			comment:{
				content:"我是来做评论的哈哈哈哈哈哈哈哈哈",
				author:"kuazhu"
			}
		},
		{
			url:"https://www.kuazhu.com",
			img:"img/shshangou1.jpg",
			name:"小米游戏本15.6 '8代i5 8G 1T 我是被省略的",
			desc:"冷酷的性能怪兽",
			price:"5999",
			del:"7999",
			flag:{
				name:"flag-jian",
				content:"立减200元"
			},
			comment:{
				content:"我是来做评论的哈哈哈哈哈哈哈哈哈",
				author:"kuazhu"
			}
		},
		{
			url:"https://www.kuazhu.com",
			img:"img/shshangou1.jpg",
			name:"小米游戏本15.6 '8代i5 8G 1T 我是被省略的",
			desc:"冷酷的性能怪兽",
			price:"5999",
			del:"7999",
			flag:{
				name:"flag-jian",
				content:"立减200元"
			},
			comment:{
				content:"我是来做评论的哈哈哈哈哈哈哈哈哈",
				author:"kuazhu"
			}
		},
		{
			url:"https://www.kuazhu.com",
			img:"img/shshangou1.jpg",
			name:"小米游戏本15.6 '8代i5 8G 1T 我是被省略的",
			desc:"冷酷的性能怪兽",
			price:"5999",
			del:"7999",
			flag:{
				name:"flag-jian",
				content:"立减200元"
			},
			comment:{
				content:"我是来做评论的哈哈哈哈哈哈哈哈哈",
				author:"kuazhu"
			}
		},
		{
			top:{
				desc:"米家电烤箱",
				price:"299",
				url:"https://www.kuazhu.com",
				img:"img/shdkx.png"
			},
			bottom:{
				name:"热门",
				url:"https://www.kuazhu.com",
				img:"img/shjiantou.png"
			}
		}
	]
];